blueprint:
  name: Bilrea Scroll Controller V1.1
  domain: automation
  author: whag
  description: >
    Control Lights, Volume, or Climate using the Bilrea/Tuya Smart Knob.
    
    INSTRUCTIONS:
    1. Enter the full MQTT Topic below. 
    2. Replace 'FRIENDLY_NAME_HERE' with your device's name from Zigbee2MQTT (e.g., 'zigbee2mqtt/my_remote').
    
    Features:
    - Smart Limit Logic: NULL = Up, 1 = Down.
    - Media player: TV Volume Up/Down commands.
    - Instant Click: Interruptible scroll loop.

  input:
    mqtt_topic:
      name: MQTT Topic
      description: "The full Zigbee2MQTT topic. Replace the end with your device name."
      default: "zigbee2mqtt/FRIENDLY_NAME_HERE"
      selector:
        text:
    
    controlled_entity:
      name: Entity to Control
      description: "The Light, Media Player, or Climate entity."
      selector:
        entity:
          domain: [light, media_player, climate]

    control_mode:
      name: Control Mode
      description: "What to control."
      default: light_brightness
      selector:
        select:
          options:
            - {label: "Light - Brightness", value: light_brightness}
            - {label: "Light - Color Temp", value: light_temp}
            - {label: "Light - Color Wheel", value: light_color}
            - {label: "Media Volume", value: media}
            - {label: "Climate Temperature", value: climate}

    step_size:
      name: Scroll Sensitivity
      description: "Change amount per click. Rec: 10 (Lights), 5 (Volume)."
      default: 10
      selector:
        number: {min: 0.1, max: 100, step: 0.1}

    session_timeout:
      name: Session Timeout
      description: "Seconds to wait after scrolling stops. Default: 2s."
      default: 2
      selector:
        number: {min: 0.5, max: 10, step: 0.5, unit_of_measurement: "s"}
    
    action_single_on:
      name: Single Click (On)
      default: []
      selector: {action: {}}
    action_single_off:
      name: Single Click (Off)
      default: []
      selector: {action: {}}
    action_double_on:
      name: Double Click (On)
      default: []
      selector: {action: {}}
    action_double_off:
      name: Double Click (Off)
      default: []
      selector: {action: {}}

mode: single
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

condition:
  - condition: template
    value_template: >
      {{ trigger.payload_json.action in ['on', 'off', 'on_double', 'off_double', 'brightness_move_to_level'] }}

variables:
  target_entity: !input controlled_entity
  mode: !input control_mode
  step: !input step_size
  timeout_secs: !input session_timeout
  topic_str: !input mqtt_topic

action:
  - choose:
      #INITIAL BUTTON CLICK
      - conditions: "{{ trigger.payload_json.action == 'on' }}"
        sequence: !input action_single_on
      - conditions: "{{ trigger.payload_json.action == 'off' }}"
        sequence: !input action_single_off
      - conditions: "{{ trigger.payload_json.action == 'on_double' }}"
        sequence: !input action_double_on
      - conditions: "{{ trigger.payload_json.action == 'off_double' }}"
        sequence: !input action_double_off

      # SCROLL SESSION START
      - conditions: "{{ trigger.payload_json.action == 'brightness_move_to_level' }}"
        sequence:
          # Capture First Value
          - variables:
              first_val: >
                {{ trigger.payload_json.brightness if trigger.payload_json.brightness is defined and trigger.payload_json.brightness != None else 255 }}

          # Calibration Wait
          - wait_for_trigger:
              - platform: mqtt
                topic: "{{ topic_str }}"
                payload: brightness_move_to_level
                value_template: "{{ value_json.action }}"
            timeout: "00:00:00.5"

          # Check Single Click
          - if:
              - condition: template
                value_template: >
                  {% set b = trigger.payload_json.brightness %}
                  {{ wait.trigger is none and (b != None and b > 1) }}
            then:
              - stop: "Single click detected or unknown direction. Ignored."

          # Calculate Initial Direction
          - variables:
              raw_second: >
                {{ wait.trigger.payload_json.brightness if wait.trigger is not none else none }}
              
              direction: >
                {% if raw_second is defined and raw_second != None %}
                  {% set sec = raw_second | int %}
                  {% if sec > first_val %} 1
                  {% elif sec < first_val %} -1
                  {% else %} 
                    {{ -1 if sec <= 1 else 1 }} 
                  {% endif %}
                {% else %}
                  {{ -1 if first_val <= 1 else 1 }}
                {% endif %}
              current_val: >
                {{ raw_second | int if raw_second is defined and raw_second != None else 255 }}

          # ENTER LOOP
          - repeat:
              sequence:
                # 1. EXECUTE MOVE
                - choose:
                    - conditions: "{{ mode == 'light_brightness' }}"
                      sequence:
                        - service: light.turn_on
                          target: { entity_id: !input controlled_entity }
                          data: { brightness_step_pct: "{{ step * direction }}", transition: 0.1 }
                    - conditions: "{{ mode == 'light_temp' }}"
                      sequence:
                        - service: light.turn_on
                          target: { entity_id: !input controlled_entity }
                          data:
                            color_temp: >
                              {% set current = state_attr(target_entity, 'color_temp') | int(370) %}
                              {% set min_m = state_attr(target_entity, 'min_mireds') | int(153) %}
                              {% set max_m = state_attr(target_entity, 'max_mireds') | int(500) %}
                              {{ [min_m, [current - (step * direction), max_m]|min]|max }}
                            transition: 0.1
                    - conditions: "{{ mode == 'light_color' }}"
                      sequence:
                        - service: light.turn_on
                          target: { entity_id: !input controlled_entity }
                          data:
                            hs_color:
                              - "{{ ( (state_attr(target_entity, 'hs_color')[0] | default(0) | float) + (step * direction) ) % 360 }}"
                              - "{{ (state_attr(target_entity, 'hs_color')[1] | default(100) | float) }}"
                            transition: 0.1
                    - conditions: "{{ mode == 'media' }}"
                      sequence:
                        - choose:
                            - conditions: "{{ direction == 1 }}"
                              sequence: [{ service: media_player.volume_up, target: { entity_id: !input controlled_entity } }]
                            - conditions: "{{ direction == -1 }}"
                              sequence: [{ service: media_player.volume_down, target: { entity_id: !input controlled_entity } }]
                    - conditions: "{{ mode == 'climate' }}"
                      sequence:
                        - service: climate.set_temperature
                          target: { entity_id: !input controlled_entity }
                          data: { temperature: "{{ state_attr(target_entity, 'temperature') | float(20) + (step * direction) }}" }

                # WAIT 
                - wait_for_trigger:
                    - platform: mqtt
                      topic: "{{ topic_str }}"
                      value_template: "{{ value_json.action is defined }}"
                  timeout: 
                    seconds: !input session_timeout

                # TIMEOUT CHECK
                - if:
                    - condition: template
                      value_template: "{{ wait.trigger is none }}"
                  then:
                    - stop: "Session ended."

                # BUTTON CHECK
                - if:
                    - condition: template
                      value_template: >
                        {{ wait.trigger.payload_json.action in ['on', 'off', 'on_double', 'off_double'] }}
                  then:
                    - choose:
                        - conditions: "{{ wait.trigger.payload_json.action == 'on' }}"
                          sequence: !input action_single_on
                        - conditions: "{{ wait.trigger.payload_json.action == 'off' }}"
                          sequence: !input action_single_off
                        - conditions: "{{ wait.trigger.payload_json.action == 'on_double' }}"
                          sequence: !input action_double_on
                        - conditions: "{{ wait.trigger.payload_json.action == 'off_double' }}"
                          sequence: !input action_double_off
                    - stop: "Loop interrupted by button click."

                # RECALCULATE
                - variables:
                    raw_new: "{{ wait.trigger.payload_json.brightness }}"
                    direction: >
                      {% if raw_new is defined and raw_new != None %}
                        {% set val = raw_new | int %}
                        {% if val > current_val %} 1
                        {% elif val < current_val %} -1
                        {% else %} {{ -1 if val <= 1 else direction }} {% endif %}
                      {% else %}
                        1
                      {% endif %}
                    current_val: >
                      {{ raw_new | int if raw_new is defined and raw_new != None else 255 }}

              while: "{{ true }}"
